version: '3.6'

services:
  nodejs:
    image: gonzaagb/flxserviceapi:1.2
    networks:
      - traefik
      - default
    volumes:
      - 'nodejs_data:/app/data'
    ports:
      - '10000:5000'
    deploy:
      labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.${FQDN_NOTDOT}-http.entrypoints=web" 
      - "traefik.http.routers.${FQDN_NOTDOT}-http.rule=Host(`${PS_DOMAIN}`) || Host(`www.${PS_DOMAIN}`)" 
      - "traefik.http.middlewares.${FQDN_NOTDOT}-http.redirectscheme.scheme=https"
      - "traefik.http.routers.${FQDN_NOTDOT}-https.rule=Host(`${PS_DOMAIN}`) || Host(`www.${PS_DOMAIN}`)"
      - "traefik.http.routers.${FQDN_NOTDOT}-https.entrypoints=https"
      - "traefik.http.routers.${FQDN_NOTDOT}-https.tls=true"
      - "traefik.http.routers.${FQDN_NOTDOT}-https.tls.certresolver=myresolver"
      - "traefik.http.services.${FQDN_NOTDOT}-http.loadbalancer.server.port=5000"
      placement:
        constraints: ["${NODE}"]
      resources:
        limits:
          cpus: '1.0'
          memory: 1.0G

volumes:
  nodejs_data:
    name: "${FQDN_NOTDOT}_nodejs-data"

networks:
  traefik:
    external:
      name: traefik-network
